'use strict';
const assert=require('node:assert/strict'); const test=require('node:test');
const {createRadarDocumentationRecord}=require('../src/core/radar-documentation-record');
function document(overrides={}){return {document_id:'radar-document:v1:001',document_type:'VERIFIED_RADAR_RECORD',radar_id:'radar:v1:001',radar_type:'EARLY_FORMATION',state:'VERIFIED',validation_result:'CONFIRMED',lineage:{summary_id:'summary:v1:001',intelligence_id:'intelligence:v1:001',formation_id:'formation:001',outcome_id:'outcome:001',validation_id:'validation:001'},evidence_ids:['evidence:001','evidence:002'],...overrides};}
test('creates a deterministic documentation record',()=>{const r=createRadarDocumentationRecord({document:document()});assert.match(r.record_id,/^radar-document-record:v1:[a-f0-9]{64}$/);assert.equal(r.state,'VERIFIED');});
test('record identity is deterministic',()=>{const a=createRadarDocumentationRecord({document:document()}),b=createRadarDocumentationRecord({document:document()});assert.equal(a.record_id,b.record_id);});
test('record isolates caller-owned input',()=>{const input={document:document()},r=createRadarDocumentationRecord(input);input.document.evidence_ids.push('evidence:003');r.evidence_ids.push('evidence:004');assert.deepEqual(r.evidence_ids,['evidence:001','evidence:002']);assert.deepEqual(input.document.evidence_ids,['evidence:001','evidence:002','evidence:003']);});
test('invalid document type is rejected',()=>assert.throws(()=>createRadarDocumentationRecord({document:document({document_type:'OTHER'})}),/DOCUMENT_TYPE_INVALID/));
test('invalid document state is rejected',()=>assert.throws(()=>createRadarDocumentationRecord({document:document({state:'HISTORICAL'})}),/DOCUMENT_STATE_INVALID/));
test('duplicate evidence is rejected',()=>assert.throws(()=>createRadarDocumentationRecord({document:document({evidence_ids:['evidence:001','evidence:001']})}),/EVIDENCE_IDS_DUPLICATE/));