"use strict";
const dns=require("node:dns").promises;
const {executeAcquisition}=require("./acquisition-runtime");
const {writeExecutionState,readExecutionState}=require("./execution-state");
async function resolveAddresses(target){const url=new URL(target);const addresses=await dns.lookup(url.hostname,{all:true,verbatim:true});return [...new Set(addresses.map(x=>x.address))];}
function createBackendRegistry(backends){if(!backends||typeof backends!=="object"||Array.isArray(backends))throw new TypeError("BACKENDS_REQUIRED");const out={};for(const [name,backend] of Object.entries(backends)){if(!backend||typeof backend.acquire!=="function")throw new TypeError("BACKEND_INVALID");out[name]=backend;}return Object.freeze(out);}
async function runCycle({request,backends,owner,statePath,now,leaseTtlMs}){const registry=createBackendRegistry(backends),backend=registry[request.backend];if(!backend)throw new Error("BACKEND_NOT_REGISTERED");const resolvedAddresses=await resolveAddresses(request.target);const execution=await executeAcquisition(request,backend,{owner,now,leaseTtlMs,resolvedAddresses});if(statePath){const previous=readExecutionState(statePath);writeExecutionState(statePath,{runtime_id:execution.execution_id,request_id:request.request_id,revision:(previous?.revision||0)+1,last_checkpoint:execution.checkpoints.at(-1),updated_at:now?now().toISOString():new Date().toISOString()});}return execution;}
async function runContinuous({requests,backends,owner="a9-runtime",statePath,intervalMs=0,maxCycles=1,now}){if(!Array.isArray(requests)||requests.length===0)throw new TypeError("REQUESTS_REQUIRED");if(!Number.isInteger(maxCycles)||maxCycles<=0)throw new TypeError("MAX_CYCLES_INVALID");if(!Number.isInteger(intervalMs)||intervalMs<0)throw new TypeError("INTERVAL_INVALID");const results=[];for(let cycle=0;cycle<maxCycles;cycle++){for(const request of requests)results.push(await runCycle({request,backends,owner,statePath,now}));if(cycle+1<maxCycles&&intervalMs>0)await new Promise(r=>setTimeout(r,intervalMs));}return Object.freeze(results);}
module.exports={resolveAddresses,createBackendRegistry,runCycle,runContinuous};
